# Generated by Django 5.2 on 2025-06-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField()),
                ('age', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='person')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
